configfile: 'config.yaml'

# Load the list of samples from the sample list file
with open(config['sample_list_file']) as f:
    samples_list = [line.strip() for line in f if line.strip()]

include: 'rules/imputation.smk'

wildcard_constraints:
    sample='|'.join(samples_list),
    chr='|'.join(["chr" + str(i) for i in range(1,23)])

rule all:
    input:
        imputes=expand("results/{sample}/{sample}.{chr}.impute.vcf.gz",sample=samples_list,chr=["chr" + str(i) for i in range(1,23)])