# Configuration for the Pangenome construction and Annotation

# Path of reference genomes
# Files could be download from https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.40_GRCh38.p14/GRCh38_major_release_seqs_for_alignment_pipelines/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz
grch38: "/storage/reference/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"
# Files could be download from https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/assemblies/analysis_set/chm13v2.0_maskedY_rCRS.fa.gz
chm13: "/storage/reference/chm13v2.0_maskedY_rCRS.fa"

# Path of assemblies
fa: "../01_Assembly/results/{sample}/{sample}.{haplotype}.fasta"
# Path of merged annotation
anno: "../01_Assembly/results/{sample}/{sample}.{haplotype}.type.final.bed"

# Path of sample list
sample_list_file: "data/samples.txt"

# Path of brnn model
brnn_knm: "data/attcc-alpha.knm"

# Path of Illumina sequencing data
sr_fq1: "../01_Assembly/data/seq/{sample}/{sample}-WGS.R1.fastq.gz"
sr_fq2: "../01_Assembly/data/seq/{sample}/{sample}-WGS.R2.fastq.gz"