# Configuration for the Medical relevance analysis

# Path of reference genomes
# Files could be download from https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.40_GRCh38.p14/GRCh38_major_release_seqs_for_alignment_pipelines/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz
grch38: "/storage/reference/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"

# Path of GENCODE annotation
# Files could be download from https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_49/gencode.v49.annotation.gtf.gz
gencode: "/storage/reference/gencode.v49.annotation.gtf"

# Path of sample list
sample_list_file: "data/samples.txt"

# Path of GRCh38 Flagger common unreliable regions
unreliable_bed: "data/grch38.flagger.unreliable.bed"

# Path of assemblies
fa: "../01_Assembly/results/{sample}/{sample}.{haplotype}.fasta"

