# Configuration for the Haplotype Assembly and Contig Cleaning

# Path of sequencing data for the pipeline, including PacBio HiFi, Hi-C, Illumina WGS, and RNA-seq data
hic_fq1: "data/seq/{sample}/{sample}-HiC.R1.fastq.gz"
hic_fq2: "data/seq/{sample}/{sample}-HiC.R2.fastq.gz"
hifi_fq: "data/seq/{sample}/{sample}-HiFi.fastq.gz"
sr_fq1: "data/seq/{sample}/{sample}-WGS.R1.fastq.gz"
sr_fq2: "data/seq/{sample}/{sample}-WGS.R2.fastq.gz"
rna_fq1: "data/seq/{sample}/{sample}-RNA.R1.fastq.gz"
rna_fq2: "data/seq/{sample}/{sample}-RNA.R2.fastq.gz"

# Path of sample List
sample_list_file: "data/samples.txt"

# Path of GRCh38 reference genome
# Files could be download from https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.40_GRCh38.p14/GRCh38_major_release_seqs_for_alignment_pipelines/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz
reference: "/storage/reference/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"

# Path of GENCODE annotation
# Files could be download from https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_49/gencode.v49.annotation.gff3.gz
gencode: "/storage/reference/gencode.v49.annotation.gff3"

# Path of NCBI Refseq data with non-human (bacteria, viruses_and_viroids, archaea, fungi) genomes and blast index
# Files could be download from https://ftp.ncbi.nlm.nih.gov/refseq/release/ and indexed using BLAST
refseq_dir: "/storage/Refseq"
# Path of non-human accession in the RefSeq
nonhuman_accession: "data/non-human.accession.list"

# Path of PacBio adaptor data
adaptor: "data/pacbio.adaptor.fa"

# Path of SEI model
# Files could be download from https://zenodo.org/records/4906997/files/sei_model.tar.gz?download=1
sei_model_path: "data/sei.pth"
clustervfeat_path: "data/projvec_targets.npy"