configfile: 'config.yaml'

# Load the list of samples from the sample list file
with open(config['sample_list_file']) as f:
    samples_list = [line.strip() for line in f if line.strip()]

include: 'rules/eqtl_mapping.smk'
include: 'rules/gene_expression.smk'

wildcard_constraints:
    sample='|'.join(samples_list)

rule all:
    input:
        sig="results/merge.eqtl.txt",
        cond="results/merge.cond.eqtl.txt",
        susie="results/merge.susie.eqtl.txt",
        top="results/merge.top.eqtl.txt"
